version: 2.1

jobs:
  
  build-medium-arm64:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    working_directory: ~/moviepy
    steps:
      - run: uname -a
      - run: echo "Hello, Arm!"
      - checkout
      - run:
          name: ️️🏗️ pip dev requirements
          command: |
            uname -m
            sudo apt-get install python3 && sudo apt-get install python3-pip
            python3 --version
            pip3 install --upgrade virtualenv --progress-bar off
            python3 -m venv venv || virtualenv venv && . venv/bin/activate
            python3 -m pip install --upgrade pip
            python3 -m pip install pytest
            python3 setup.py install
            python3 -m pip install --upgrade wheel setuptools
            python3 -m pip install python-dotenv
            python3 -m pip install -e .[test]
            python3 -m pip install ".[test, optional, doc]"
            apt install ffmpeg -y
            apt install imagemagick -y
            python3 -m pytest --doctest-glob "moviepy/**/**.py" --cov moviepy --cov-report term-missing
            
workflows:
  version: 2
  python3.7:
    jobs:
      - build-medium-arm64
